### ISSUE TITLE
[Feature request] Add warning for code errors similar to the Theme / Plugin Editor

### ISSUE THREAD

**Issue by pr0jectile** [sheabunge/code-snippets#103]
Hi there,

Are you planning to add a feature to this plugin which alerts the user that there is broken syntax / code errors upon saving, instead of the site breaking, which leads you into the rabbit hole of the database and cleaning out the problem?

The default Theme Editor and Plugin Editor has this built in and I was wondering if you could utilise something like this.

Would save those in a pinch :)

Thanks in advance!

**Comment by Jetxpert** [comment]
Good Day!

Adding your feature to the plugin is not a bad idea. However, it would add a maintenance burden to the plugin that the developer may not wish to pursue.

Until the developer has a chance to review and comment on your feature request, you can always use the PHP Code Checker tool provided below BEFORE you create and save your code snippet.

https://extendsclass.com/php-tester.html

Cheers!

**Comment by sheabunge** [comment]
This is something we've already attempted to implement, and will be doing what we can to refine in future. It's unfortunately impossible to do things exactly as the theme and plugin editor do at this point due to differences in how snippets work, but we currently have real-time validation, and both pre-save syntax/duplicate identifier validation and pre-save evaluation, which should hopefully catch most of these issues.
