### ISSUE TITLE
Issues with Content Snippet Block in Gutenberg

### ISSUE THREAD

**Issue by deckerweb** [sheabunge/code-snippets#133]
**Describe the bug**
I have 2 HTML Content Snippets in CS Pro, just for testing. So far so good.
- PHP Shortcode Current year plus added paragraph - snippet works well
- Simple Div container and some text.

If I want to add one of these with the Gutenberg "Content Snippet" block the block does almost nothing or looks like it is endlessly loading. I double checked if both snippets are activated (they were!). Reloaded the page I was editing in Gutenberg. The first snippet (the div container) appeared in the dropdown and I could insert. It is also showing properly.

Just below added 2nd Content Snippet block - no snippet appears in the dropdown. After reload of page I see it, insert it, but does not work. Also the whole block seems like empty on the page. But when in List View (Block Navigator) I see the block there.

**Expected behavior**
Insert block, all proper snippets appear in dropdown I would select one and done. Add as many Content Snippet blocks as I want – same procedure all would work.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 102.0
 - Version: CS Pro 3.1.2.1
 
**Additional context**
In general I would improve the user guidance a bit.
I understand that this Gutenberg block is for the HTML snippet type only? Would make sense, I guess. But it is not crystal clear in the snippet edit view and also not in the block editor.

I would add these additional user info within the block or in the block sidebar. Also if this is technically possible I would ADDITIONALLY add these options from the Snippet edit view to the block edit / sidebar:
"Shortcode Options: Evaluate PHP code | Add paragraphs and formatting | Evaluate additional shortcode tags"

**Comment by sheabunge** [comment]
Thank you for reporting this. I am aware of the issue with the snippets not loading, and I'm preparing a release to fix. Unfortunately, loading data from the server isn't the easiest thing to do in Gutenberg – it seems to be primarily designed for more basic, less dynamic blocks. 

Content snippets are for the HTML type only (or 'Content' snippets), because those are the only ones designed to produce content/output. If you have any suggestions for how additional snippet types might be useful in the editor, we'd definitely love to hear them.  I'll also see what I can do about adding something in here to explain things a bit better.

I am a little bit confused by the last suggestion. Those options should already be visible in the block editor sidebar. Are they not showing up on your site?  

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1170783/177292244-4f5593d1-f6b4-41c7-ba23-350bb3ee4dbc.png">

**Comment by deckerweb** [comment]
mmh strange, I don't see these block options within the block sidebar, so I initially thought there are none so far...

I have to test on another site - maybe it was me/my environment, just getting back on this shortly

**Comment by deckerweb** [comment]
Tested in another environment and there the block settings/sidebar for the Content Snippet block appears properly. The other issue remains there also.

**Comment by sheabunge** [comment]
Should be fixed in v3.2.0. Thanks again for reporting!
