### ISSUE TITLE
Automatically hide admin alerts

### ISSUE THREAD

**Issue by luizbills** [sheabunge/code-snippets#169]
Now that codes are saved asynchronously, it would be interesting for notices ("Snippet updated" and errors) to be hidden after a few seconds so they don't accumulate. It would also be interesting to show these notices as "toasts" in the corner of the screen, because the top will not always be visible.

**Comment by GermanKiwi** [comment]
See also the discussion in the comments under this post:
https://www.facebook.com/groups/codesnippetsplugin/posts/1291501484807926/

**Comment by sheabunge** [comment]
Thanks for the suggestion, both!

We've discussed some potential options here. I think we've settled on only ever displaying the latest notice, instead of allowing them to build up.

The issue with having the notices just automatically dismiss is that it will cause the page content to jump up as it disappears, which I imagine could present some annoyances.

**Comment by sheabunge** [comment]
Fixed in 4d9709b9af34967e8166d95d74a8d47eed62c593.
