### ISSUE TITLE
Add different snippet types

### ISSUE THREAD

**Issue by sheabunge** [sheabunge/code-snippets#28]
In order to make this plugin more useful in different situations, I would like to implement support for CSS code snippets, and HTML snippets that can be inserted into posts through a visual editor button.

I suggest having three tabs on the edit snippet page: Functions, Styles, and Content. Functions are the executable PHP code snippets, styles are CSS snippets that will be concatenated into a stylesheet and linked either on the admin area or the front-end, and Content will be HTML (PHP?) snippets that are designed for inserting into posts. On each tab should be a short description of what the type does.

Each tab could also include type-specific settings. For example, the scope selector for function snippets, a similar one for CSS snippets, perhaps a shortcode identifier for content snippets.

**Comment by signo** [comment]
The html snippets i don´t know, html code depends on where it is placed and since php is there to generate html and the hooks and filters are the method that control where in the html should the code be inserted, i think html is already covered with regular php snippets.

I like the CSS snippets, they are very easy to insert in the code, you could enhance them with a conditional (eval) to determine if the CSS should be inserted or not.

The other one you could add  is JavaScript Snippets, you could ask where to place them in the header or footer and could use the conditional too.

**Comment by dnavarrojr** [comment]
I don't think adding support for HTML snippets would hurt developers and it could have its uses.

For CSS snippets, scope would be great.  (insert in header, insert in footer, insert in admin).

**Comment by jasonday** [comment]
I think javascript snippets would be great.

**Comment by ajiuo666** [comment]
Yes! Pleas add CSS snippets. Java and HTML would also be cool. There is another plugin that does CSS, java, html... but no php. I The Ui of this plugin better and would like to see it handle all 4

**Comment by sheabunge** [comment]
This is under development for version 3, so I'm closing this. Please feel free to comment with more suggestions on how you'd like to see it implemented.
