### ISSUE TITLE
Save Code Snippet as Shortcode

### ISSUE THREAD

**Issue by marbetschar** [sheabunge/code-snippets#42]
It would be great if we can save a snippet and insert it execute it in any post by using a shortcode.

**Comment by sheabunge** [comment]
So instead of action/filter snippets, you mean snippets which generate output? e.g.:

```php
Copyright <?php date( 'Y' ); ?>
```

If so, this links into the [planned snippet types system](https://github.com/sheabunge/code-snippets/issues/28) as a "content" snippet.

**Comment by marbetschar** [comment]
That's exactly what I meant! Glad too see there are already plans for it!

I know all of this is open source and it needs some additional time & love despite the regular work; not to forget the holidays going on right now.

But do you have already any priority list, ETA or roadmap for the enhancements? I would really love to see those as soon as possible and I'm also keen on helping with them as good as I can.

**Comment by sheabunge** [comment]
I don't really have a proper roadmap, just a few emails in my inbox and a messy list in Trello. I should work on building one though. The thing is, I'm not sure exactly the direction in which to take this plugin, as changes like these are a pretty significant update, which would require a lot of redesigning instead of simply building on existing code.

But I'll be working on this whenever I have the time - I am going away in January, so I'm not sure how much progress I will be able to make then, unfortunately.

**Comment by sheabunge** [comment]
I'm closing this as it seems to be a duplicate of #28.
