### ISSUE TITLE
Request/suggestion: Please create a paid pro version

### ISSUE THREAD

**Issue by Ver3** [sheabunge/code-snippets#66]
Hi @sheabunge ,

Even since we started using the Code Snippets Extension from MainWP, all our sites have become dependent on your plugin to function properly. We love it, but we also worry that one day you may lose interest and stop supporting it.

So allow me to paint a (probably unrealistic) ideal picture:

1. A customer pays you 19 a year or 59 for a lifetime account (just an example) without support OR 49 a year and 129 for lifetime including non-content related support.
2. They receive a code that unlocks extra functionality (no extra pro plugin please). If this extra functionality could be [support for CSS snippets](https://github.com/sheabunge/code-snippets/issues/57), that would save installing yet another plugin and make CSS manageable for all site from one dashboard if they also use MainWP.
3. You receive a lot of income, enough to keep developing this plugin and make room for other projects by hiring someone to do support (and so you not get bored doing just one thing).

Indeed, this is around the time I woke up fro the dream above. Do not take it all literally, but please consider a paid version to ensure continuity.

Cheers and thanks again for making my dev-life easier ;-)

**Comment by Ver3** [comment]
Ps. Two more suggestions that just came to mind:

1. Update your website to highlight Code Snippets and add new snippet examples.
2. Provide a way for users to share their favorite snippets with each other.

Cheers.

**Comment by sheabunge** [comment]
Hey @Ver3,

Thank you for getting in touch, I really appreciate it.

I do really like your suggestions, and they have definitely given me a lot to think about. At the moment it's a matter of balancing a number of different projects and other things such as study together, but I would love to be able to devote more time to this project. 

Regarding the idea of adding premium unlockable features, do you think that it would be best to hold off from introducing new features such as CSS snippets into the core plugin until I have a premium based model set up, or would it be best to introduce them as soon as possible, and then rework things into a premium model later on?

A paid version of the plugin is something that I have thought of before, but haven't really considered it seriously because I feel like it would take a lot of careful planning and time to introduce well, and for the moment I've been more focused on trying to implement and release new features for everyone to use, and strengthen the plugin as a whole. I do really appreciate posts and suggestions like these, as they provide me with a clearer picture of what something like this might look like, and reassure me that it might be viable. 

Regarding your second lot of suggestions, a snippet sharing site would definitely be a fantastic idea, and it's one I've been wanting to put together for some time now. Unfortunately, this also comes under the area of wanting to devote any time I can spend on this plugin to strengthening the core plugin as a whole.

**Comment by Ver3** [comment]
Hi Shae,

Thanks for getting back to me so quickly. In answer to your questions (from
the perspective of a business owner):

*Do you think that it would be best to ... into a premium model later on?*
Both.

1. Start with a select group of loyal users, let them use a polished beta
and set up a feedback form (er better, a beta-board in Trello. Let me know
if you want help with that). These are your ambassadors. These are the
people who will spread the word in their communities that a Pro version is
coming and that we can finally and officially support you (not just by
donating like I did last week anyway :-)

2. In the meantime collect feedback, thank everybody for it, set up your
pro-key admin and new small site explaining all your plugin does. Test that
too, then launch.

Tip: For the small single product site. Ask beta users for their favorite
snippets and if they would like to share them (with their name added
for 'street cred'). Then later add these to the site or allow all paying
users to share their work using a form that puts it online (after your
check).

As for your time problem, I can only recommend a minddump to save time. The
rest is up to your personal priorities. If I can help in any way though,
I'll be happy to!

Cheers!

Verdi.

**Comment by Ver3** [comment]
Hi @sheabunge ,

Thanks for getting back to me so quickly. In answer to your question (from
the perspective of a business owner):

### Do you think that it would be best to ... into a premium model later on?

Both.

1. Start with a select group of loyal users, let them use a polished beta
and set up a feedback form (er better, a beta-board in Trello. Let me know
if you want help with that). These are your ambassadors. These are the
people who will spread the word in their communities that a Pro version is
coming and that we can finally and officially support you (not just by
donating like I did last week anyway :-)
2. In the meantime collect feedback, thank everybody for it, set up your
pro-key admin and new small site explaining all your plugin does. Test that
too, then launch.

Tip: For the small single product site. Ask beta users for their favorite
snippets and if they would like to share them (with their name added
for 'street cred'). Then later add these to the site or allow all paying
users to share their work using a form that puts it online (after your
check).

As for your time problem, I can only recommend doing a minddump to save time. The
rest is up to your personal priorities. If I can help in any way though,
I'll be happy to! Naturally, I'd love to be at least a beta user.

Cheers!

Verdi.

**Comment by Ver3** [comment]
@sheabunge 

One more suggestion, in case you ever decide to support CSS:

In the 'edit snippet' screen there is a title called 'Code'. It would be awesome if this becomes a tab, net to the tab 'CSS'. A user can choose to fill in either or both. 

This way you always have the CSS and PHP code together for the thing a user is trying to accomplish. If ever a user needs to change or remove 'that thing', this will save a lot of time.

Hope this suggestion helps. Cheers.

**Comment by Ver3** [comment]
@sheabunge See my last two posts, any of it usable for you? Let me know if I can help in some way. Cheers.
