### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by sathisk** [sheabunge/code-snippets#69]
The latest Code Snippet plugin cannot be activated in WordPress v4.9.4. My entire WordPress site was down after the plugin update with HTTP error 500. I had to deactivate all my plugins and reactivate one by one to trace which plugin was giving the problem.

Error as follow:

### File: /home/XXXXX/public_html/wp-content/plugins/code-snippets/php/class-code-snippets.php

**Comment by ThomasChr** [comment]
Same here!

**Comment by m-e-h** [comment]
Yep, auto-update is crashing sites.
```PHP Warning: require_once(/wp-content/plugins/code-snippets/php/import-export.php): failed to open stream: No such file or directory in /wp-content/plugins/code-snippets/php/class-code-snippets.php on line 60```

**Comment by sconstan** [comment]
same in 2 of my websites where i use the plugin... was hard to pinpoint the problem as well....

**Comment by AlphaDE** [comment]
The required file "import-export.php" in /php does not exist...

**Comment by ThomasChr** [comment]
Yes, going into /wp-content/plugins/code-snippets/php and doing „wget https://raw.githubusercontent.com/sheabunge/code-snippets/develop/php/import-export.php“ did the trick. Thanks!

**Comment by maiki** [comment]
The `import-export.php` in question is not committed to the master branch, which the public repo no doubt imports and builds from.

@sheabunge could you commit that and push it to the public repo, please? 😃

**Comment by JFCote** [comment]
Same problem here.

**Comment by sheabunge** [comment]
Hey everyone,

The GitHub repository is separate from the WordPress.org subversion repository, which is where releases are actually built from. Unfortunately, there was an issue with making this transfer of files between repositories, and the `php/import-export.php` file was not uploaded correctly.

This has since been fixed, and the version number bumped up, so redownloading or updating the plugin will resolve this issue. I'm really sorry for causing this mistake, and I hope that everyone is able to update to the new version without any stress.
