### ISSUE TITLE
Admin column ID is not showing for the snippets list

### ISSUE THREAD

**Issue by studioart** [sheabunge/code-snippets#73]
Hi,

I'd like to show the ID column for my snippets, but when I mark the ID column, it shows this column, but as soon as I save it, it disappears.

I already disabled all other plugins, no success. This happens only within the Codesnippets list.

Here is an animated GIF of my backend:
http://imgbox.com/7gODmioB

- WP 4.9.8
- PHP 7.1
- Tested with Firefox Quantum 62.0 with WINDOWS 10 prof.

Could you please fix this please?
Thanks.

**Comment by sheabunge** [comment]
Hello,

Thank you very much for reporting this. It looks like this is a bug present in even the very early versions of the plugin. If you made it so no columns were hidden, the plugin would try to override this with the default of hiding the ID column.

I've changed this behaviour so that it ensures that the defaults are only applied when there are no settings saved at all. Thanks again for bringing this to my attention.
