### ISSUE TITLE
Default snippets duplicated after re-install

### ISSUE THREAD

**Issue by jancbeck** [sheabunge/code-snippets#76]
I just noticed that after I had re-installed the plugin that all the default snippets are added again. This is not a high priority but you might want to implement a simple check if they already exist before inserting them.

**Comment by sheabunge** [comment]
When you uninstall the plugin, all snippets – including default ones – should be removed from the database. So when reinstalling from scratch, it would be appropriate to add them back in.

If you are referring to a situation where the plugin is deactivated or removed without its data being cleaned up, and then reinstalled: currently, the default snippets are only added to fresh installs of the plugin, so I'm unsure how they would be duplicated like this.

I'm going to close this for now as it's possible the behaviour you are describing has been fixed in a more recent version, but if you can still identify it as a problem, let me know and I'll look into it.
