### ISSUE TITLE
Conditional Tags - WooCommerce

### ISSUE THREAD

**Issue by Camilo517** [sheabunge/code-snippets#95]
Hello, it would be nice if you have WooCommerce active, you can select the WooCommerce tag
https://docs.woocommerce.com/document/conditional-tags/

**Comment by VerdiH** [comment]
> Hello, it would be nice if you have WooCommerce active, you can select the WooCommerce tag
> https://docs.woocommerce.com/document/conditional-tags/

@Camilo517  Could you provide more details please? How would this look like, what benefit does it have for you? 

Do you mean you would be able to select the tags form a dropdownlist in a way that let's you target your Code Snippet to that specific Tag? It's seems you can do this already in the Snippet Itself. Or do you mean for the Snippet to be inserted in another place than functions.php?

Anyway, we really value all input and suggestions. We do need more info in this case.

**Comment by Camilo517** [comment]
Hi @VerdiH 
I mean conditionals here
http://prntscr.com/wm0j2x
For example run a snippet on the front-end and only in WooCommerce categories

**Comment by slomeli79** [comment]
@Camilo517 the docs on the WooCommerce page you linked already provide all the info you need to write conditional tags in your own snippet.

e.g.
```
is_product_category( array( 'shirts', 'games' ) ) {
  // do stuff
}
```

Really rather not have Code Snippets try to create options for every conceivable third-party integration. That's the whole point of writing our own snippets.

**Comment by sheabunge** [comment]
Conditional tags seem to be a fairly frequently requested feature. It'd be nice to have *some* sort of UI for more easily adding them, the issue is creating a UI that's powerful enough to support a bunch of different tags and conditions, while also avoiding becoming convoluted or overly confusing.

I might edit your original issue to reflect a more general conditional tags feature, and leave this open for any suggestions on exactly what you'd like this feature to look like, from an interface perspective,
